### ISSUE TITLE
An error occurred while executing python train.py --render

### ISSUE THREAD

**Issue by skylbc** [jeromepl/Locomotion#1]
Hello, I am running the program in Ubuntu , there is an error when executing python train.py --render, can you help me to see it?
![UL(PVTJ(MQ`4PB P_I9EV)R](https://user-images.githubusercontent.com/35951049/54983943-c190a580-4fe8-11e9-91fb-c41db42999ee.png)

**Comment by jeromepl** [comment]
Hmm, I think this is an issue with the version of Gym that you are using. Have you tried the gym version in `requirements.txt`? The version listed there is `gym==0.10.5`.

**Comment by skylbc** [comment]
ok,I will try later

**Comment by jeromepl** [comment]
Any luck?
